//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class complain
    {
        public string c_subject { get; set; }
        public string c_type { get; set; }
        public string ctg { get; set; }
        public string c_details { get; set; }
        public int c_id { get; set; }
    }
}
