//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINALEntities : DbContext
    {
        public FINALEntities()
            : base("name=FINALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<a_profile> a_profile { get; set; }
        public DbSet<adv_details> adv_details { get; set; }
        public DbSet<b_profile> b_profile { get; set; }
        public DbSet<blog> blogs { get; set; }
        public DbSet<c_rating> c_rating { get; set; }
        public DbSet<complain> complains { get; set; }
        public DbSet<s_appartment_details> s_appartment_details { get; set; }
        public DbSet<s_profile> s_profile { get; set; }
        public DbSet<t_profile> t_profile { get; set; }
        public DbSet<trans_details_sb> trans_details_sb { get; set; }
        public DbSet<user_details> user_details { get; set; }
    }
}
