//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_profile
    {
        public int id { get; set; }
        public int t_id { get; set; }
        public string t_name { get; set; }
        public string t_address { get; set; }
        public string t_email { get; set; }
        public string t_img { get; set; }
        public string t_num { get; set; }
    
        public virtual user_details user_details { get; set; }
    }
}
