//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_details_sb
    {
        public int id { get; set; }
        public Nullable<int> s_id { get; set; }
        public Nullable<int> ap_id { get; set; }
        public int b_id { get; set; }
        public int amount { get; set; }
        public Nullable<int> t_id { get; set; }
    
        public virtual s_appartment_details s_appartment_details { get; set; }
    }
}
