//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_details
    {
        public user_details()
        {
            this.a_profile = new HashSet<a_profile>();
            this.b_profile = new HashSet<b_profile>();
            this.s_profile = new HashSet<s_profile>();
            this.t_profile = new HashSet<t_profile>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int user_id { get; set; }
        public string password { get; set; }
        public string rules { get; set; }
        public string status { get; set; }
        public string img { get; set; }
    
        public virtual ICollection<a_profile> a_profile { get; set; }
        public virtual ICollection<b_profile> b_profile { get; set; }
        public virtual ICollection<s_profile> s_profile { get; set; }
        public virtual ICollection<t_profile> t_profile { get; set; }
    }
}
